# Generated by Django 6.0.5 on 2026-05-21 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Custom price if different from plan price', max_digits=10, null=True)),
                ('activation_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('language_preference', models.CharField(choices=[('EN', 'English'), ('OD', 'Odia')], default='EN', max_length=2)),
                ('reminder_days_before', models.IntegerField(default=2, help_text='Number of days before expiry to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.plan')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('REMINDER', 'Due Reminder'), ('RECEIPT', 'Payment Receipt'), ('CUSTOM', 'Custom Message')], max_length=10)),
                ('message_content', models.TextField()),
                ('language', models.CharField(default='EN', max_length=2)),
                ('video_path', models.CharField(blank=True, help_text='Path to the rendered Remotion MP4 video receipt/reminder', max_length=500, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent Successfully'), ('FAILED', 'Failed'), ('PENDING', 'Pending Send')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.customer')),
            ],
        ),
    ]
