# Generated by Django 6.0.5 on 2026-05-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_whatsapplog_status_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, help_text='Custom portal password. Fallback is last 4 digits of phone', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapplog',
            name='message_type',
            field=models.CharField(choices=[('REMINDER', 'Due Reminder'), ('RECEIPT', 'Payment Receipt'), ('CUSTOM', 'Custom Message'), ('GREETING', 'Welcome Greeting')], max_length=10),
        ),
    ]
