# Generated by Django 6.0.5 on 2026-05-23 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_password_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='setup_box_brand',
            field=models.CharField(blank=True, help_text='Setup box brand/model name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='setup_box_number',
            field=models.CharField(blank=True, help_text='Setup box serial/device number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='channels',
            field=models.TextField(blank=True, help_text='Comma-separated list of channels included in this plan', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.village'),
        ),
    ]
